### PR TITLE
propose prater testnet v1.0.1

### PR DESCRIPTION
**Pull request by q9f**
Testnet will come with prepopulates genesis state (210k validators).
* https://github.com/protolambda/eth2-testnet-genesis

```
genesis_time: 1616508000
genesis_state_root: 0x895390e92edc03df7096e9f51e51896e8dbe6e7e838180dadbfd869fdd77a659
genesis_block_root: 0xeade62f0457b2fdf48e7d3fc4b60736688286be7c7a3ac4c9a16a5e0600bd9e4
genesis_validators_root: 0x043db0d9a83813551ee2f33450d23797757d430911a9320530ad8a0eabc43efb
genesis_validators_count: 210000
genesis_active_validators_count: 210000
genesis_total_active_stake_gwei: 6720000000000000
genesis_total_balance_gwei: 6720000000000000
eth1_data:
  deposit_root: 0xd70a234731285c6804c2a4f56711ddb8c82c99740f207854891028af34e27e5e
  deposit_count: 0
  block_hash: 0x5ac670562dbf877a45039d65ec3c2e3402a40eda9b1dba931c2376ab7d0927c2
deposit index: 0
genesis_fork_version: 0x00001020
genesis_fork_digest: 0x79df0428
pre_genesis_fork_digest: 0xe4be9393
```

### CODE REVIEW

**Comment by q9f** [comment]
Updated to 210k validators.

**Comment by zah** [comment]
What was the intention behind the empty genesis.ssz file added here?

**Comment by q9f** [comment]
> What was the intention behind the empty genesis.ssz file added here?

It's not empty, this is a Github UI bug. (If you click it, it shows an actual file size.)

The genesis contains 210k genesis deposits so we don't have to spam the Goerli testnet with 210k deposit transactions.

**Comment by q9f** [comment]
Shall we discuss this on Thursday and wait with merging or merge early and follow up on Thursday?

**Comment by arnetheduck** [comment]
> a few instances of non-finality due to one group or another 

this is a feature :)

**Comment by arnetheduck** [comment]
One thing about pre-populated validators that  should be noted is that it stresses the eth1 deposit pipeline a lot less, which might skew some of the test outcomes, also with respect to eth1 deposit merkle root processing.

**Comment by mcdee** [comment]
> this is a feature :)

Not when you're trying to test out your own systems it isn't :)

I recognise that having periods of non-finality to test out how clients react is no bad thing, but doing it ad-hoc is a bit of a pain.  I know that any testnet has two conflicting use cases (testbed for potential mainnet users and situational node testing for client developers) but it would be great if perhaps there were specific time periods set aside for testing that causes finality issues.  Or just some advance warning.

(Note I'm not advocating having two separate testnets; even though it would solve this problem it would bring its own hassles.)

**Comment by mcdee** [comment]
@q9f can I request some genesis validators?  This would be for our on-going work with Vouch.  16K would be about right (large enough to give it a proper working out, small enough that it wouldn't disrupt the network if it hit issues).

**Comment by arnetheduck** [comment]
> one group or another

pyrmont was 20% each split between 5 groups - 4 genesis clients and the EF - meaning at least 2 would have to be offline to get finality issues - generally, this seems like a reasonable split and while there may be other interested parties, spreading it further increases the risk of some groups losing interest and thus tightening the margin - at that point, one should consider general criteria for genesis allocation.

**Comment by mcdee** [comment]
Not sure how well that gels with the reported numbers.  https://pyrmont.beaconcha.in/charts/participation_rate shows participation dropping to ~87% on 8th December and never recovering, so there is something more than a simple binary on/off for each 20% allocation.  It seems enough were offline to create a new baseline such that a single group going fully offline resulted in lack of finality.

I suppose it isn't the allocation that is so important as the activity of the validators.  As I say, it would be nice if any planned tests that would include lack of finality were known about by the broader community in advance.

**Comment by prestonvanloon** [comment]
Is there a `genesis.ssz` uploaded anywhere?

**Comment by q9f** [comment]
> Edit: the one in the PR is an empty file.

It's a Github UI bug. It's not empty.

**Comment by q9f** [comment]
Ok this is good to go @eth2-clients/ethereum-foundation

**Review by terencechain — APPROVED** [review]

**Comment by q9f** [comment]
Merging and starting to hand out keys. If there is anything, we can amend it.

**Pull request merged**
